use std::{fmt::Display, path::Path};

#[derive(Hash, Debug, Copy, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub enum FileType {
    Image,
    Video,
    Document,
    Executable,
    Archive,
    Audio,
    Code,
    GenomicData,
    Other,
}

impl Display for FileType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{:?}", self)
    }
}

impl FileType {
    pub fn from_path<P: AsRef<Path>>(path: P) -> Self {
        let ext = path
            .as_ref()
            .extension()
            .unwrap_or(path.as_ref().file_name().unwrap_or_default())
            .to_ascii_lowercase()
            .to_str()
            .unwrap_or_default()
            .to_owned();
        FileType::get_filetype(&ext)
    }

    pub fn get_filetype<S: AsRef<str>>(ext: &S) -> Self {
        match ext.as_ref().to_lowercase().as_str() {
            "jpg" => Self::Image,
            "jpeg" => Self::Image,
            "jpegxl" => Self::Image,
            "png" => Self::Image,
            "tiff" => Self::Image,
            "raw" => Self::Image,
            "nef" => Self::Image,
            "webp" => Self::Image,
            "psd" => Self::Image,
            "heic" => Self::Image,
            "gif" => Self::Image,
            "avif" => Self::Image,
            "dng" => Self::Image,
            "svg" => Self::Image,
            "bmp" => Self::Image,

            "mp4" => Self::Video,
            "mkv" => Self::Video,
            "avi" => Self::Video,
            "webm" => Self::Video,
            "flv" => Self::Video,
            "f4v" => Self::Video,
            "gifv" => Self::Video,
            "mpeg" => Self::Video,
            "mpg" => Self::Video,
            "mov" => Self::Video,
            "wmv" => Self::Video,
            "3gp" => Self::Video,
            "aaf" => Self::Video,
            "avchd" => Self::Video,

            "pdf" => Self::Document,
            "txt" => Self::Document,
            "docx" => Self::Document,
            "doc" => Self::Document,
            "xlsx" => Self::Document,
            "xls" => Self::Document,
            "csv" => Self::Document,
            "tsv" => Self::Document,
            "md" => Self::Document,
            "odt" => Self::Document,
            "fodt" => Self::Document,
            "pages" => Self::Document,
            "rtf" => Self::Document,
            "tex" => Self::Document,
            "latex" => Self::Document,
            "epub" => Self::Document,
            "kpub" => Self::Document,
            "ppt" => Self::Document,
            "pptx" => Self::Document,
            "otp" => Self::Document,
            "odp" => Self::Document,
            "pot" => Self::Document,
            "pps" => Self::Document,
            "bib" => Self::Document,
            "log" => Self::Document,
            "tmp" => Self::Document,
            "temp" => Self::Document,

            "py" => Self::Code,
            "pyc" => Self::Code,
            "pyo" => Self::Code,
            "xml" => Self::Code,
            "html" => Self::Code,
            "htm" => Self::Code,
            "htmx" => Self::Code,
            "xhtml" => Self::Code,
            "xht" => Self::Code,
            "css" => Self::Code,
            "js" => Self::Code,
            "jsx" => Self::Code,
            "json" => Self::Code,
            "yaml" => Self::Code,
            "toml" => Self::Code,
            "ts" => Self::Code,
            "c" => Self::Code,
            "cpp" => Self::Code,
            "h" => Self::Code,
            "rs" => Self::Code,
            "r" => Self::Code,
            "go" => Self::Code,
            "zig" => Self::Code,
            "awk" => Self::Code,
            "cs" => Self::Code,
            "csproj" => Self::Code,
            "ici" => Self::Code,
            "ipynb" => Self::Code,
            "kt" => Self::Code,
            "lua" => Self::Code,
            "php" => Self::Code,
            "pl" => Self::Code,
            "pm" => Self::Code,
            "ps1" => Self::Code,
            "sh" => Self::Code,
            "fish" => Self::Code,
            "asm" => Self::Code,
            "d" => Self::Code,
            "vim" => Self::Code,
            "java" => Self::Code,
            "lisp" => Self::Code,
            "php3" => Self::Code,
            "php4" => Self::Code,
            "php5" => Self::Code,
            "phps" => Self::Code,
            "vb" => Self::Code,
            "sql" => Self::Code,

            "exe" => Self::Executable,
            "apk" => Self::Executable,
            "o" => Self::Executable,
            "so" => Self::Executable,
            "app" => Self::Executable,
            "dll" => Self::Executable,
            "elf" => Self::Executable,
            "jar" => Self::Executable,
            "lib" => Self::Executable,

            "mp3" => Self::Audio,
            "aiff" => Self::Audio,
            "aif" => Self::Audio,
            "aifc" => Self::Audio,
            "wav" => Self::Audio,
            "flac" => Self::Audio,
            "wma" => Self::Audio,
            "dts" => Self::Audio,
            "ac3" => Self::Audio,
            "aac" => Self::Audio,
            "ots" => Self::Audio,
            "ogg" => Self::Audio,

            "gz" => Self::Archive,
            "gzip" => Self::Archive,
            "zst" => Self::Archive,
            "zstd" => Self::Archive,
            "zip" => Self::Archive,
            "7z" => Self::Archive,
            "7zip" => Self::Archive,
            "rar" => Self::Archive,
            "tar" => Self::Archive,
            "bin" => Self::Archive,
            "dat" => Self::Archive,
            "bz2" => Self::Archive,
            "pak" => Self::Archive,
            "par" => Self::Archive,
            "pax" => Self::Archive,
            "sqlite" => Self::Archive,
            "sq" => Self::Archive,
            "vbox" => Self::Archive,

            "bam" => Self::GenomicData,
            "bai" => Self::GenomicData,
            "sam" => Self::GenomicData,
            "bed" => Self::GenomicData,
            "gtf" => Self::GenomicData,
            "gtf2" => Self::GenomicData,
            "gtf3" => Self::GenomicData,
            "gff" => Self::GenomicData,
            "gff2" => Self::GenomicData,
            "gff3" => Self::GenomicData,
            "bedpe" => Self::GenomicData,
            "cram" => Self::GenomicData,
            "sra" => Self::GenomicData,
            "fastq" => Self::GenomicData,
            "fasta" => Self::GenomicData,
            "fa" => Self::GenomicData,
            "fq" => Self::GenomicData,
            "fasterq" => Self::GenomicData,
            "embl" => Self::GenomicData,
            "genbank" => Self::GenomicData,
            "pdb" => Self::GenomicData,
            "ncbi" => Self::GenomicData,
            "maf" => Self::GenomicData,
            "nwk" => Self::GenomicData,
            "phd" => Self::GenomicData,
            "vcf" => Self::GenomicData,
            "pod5" => Self::GenomicData,

            _ => Self::Other,
        }
    }
}
